### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Ana-Green** [Virtual-Universe/Virtual-Universe-Early-Dev#11]
not  sure what  simulator  to  use at  all   now i  got these  warnings
Code    Description    Project    File    Line    Suppression State
CS0234    The type or namespace name 'Collection' does not exist in the namespace 'System' (are you missing an assembly reference?)    OpenSim.Region.ScriptEngine.Shared.Api.Runtime    

C:\Users\K-Zero\Pictures\Virtual-Universe-NXG-master\OpenSim\Region\ScriptEngine\Shared\Api\Runtime\OSSL_Stub.cs    31    N/A
Code    Description    Project    File    Line    Suppression State
CS0006    Metadata file 'C:\Users\K-Zero\Pictures\Virtual-Universe-NXG-master\VirtualUniverse\bin\OpenSim.Region.ScriptEngine.Shared.Api.Runtime.dll' could not be found    Gloebit    C:\Users\K-Zero\Pictures\Virtual-Universe-NXG-master\addon-modules\Gloebit\GloebitMoneyModule\CSC    1    N/A

Ana

**Comment by BritanyannStarfinder** [comment]
Closing this issue as this appears to be fixed.  If there is still an issue with building, then please open a new issue.

This had been fixed locally but I had forgotten to actually add the commit in the local repository in-house for the gitbot to push to this repository here.

Britanyann Starfinder
Core Developer
Scripting Engine Development, Maintenance
Second Galaxy Development Team
