### ISSUE TITLE
OpenSimSearch commit: f40d8fba54f0a8447831eb01ac63f3a2ba1864ee  

### ISSUE THREAD

**Issue by Ana-Green** [Virtual-Universe/Virtual-Universe-Early-Dev#17]
Sorry guys that  I have to bring this up again, in the previous build taken from GitHub   OpenSimSearch.dll is not building it's not even touched probably not in the build XML file. 
The same did happen just with commit: f40d8fba54f0a8447831eb01ac63f3a2ba1864ee

Regard,
Ana Green

**Comment by NoahStarfinder** [comment]
Closing as this has been fixed
